<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Authors>Wellington Silva</Authors>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <Product>LeitoraHU20</Product>
    <Description>Lê o número serial da leitora biométrica HU20 da Secugen</Description>
    <Copyright>Copyright © 2026 Wellington Silva</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SecuGen.FDxSDKPro.DotNet.Windows">
      <HintPath>.\SecuGen.FDxSDKPro.DotNet.Windows.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- Copia as DLLs nativas para o diretório de saída -->
  <ItemGroup>
    <None Update="sgfplib.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="sgbledev.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="sgfdusdax64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="sgfpamx.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="sgwsqlib.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- Copia o assembly da SecuGen para o diretório de saída -->
  <ItemGroup>
    <None Update="SecuGen.FDxSDKPro.DotNet.Windows.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
